import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {User} from '@supabase/supabase-js';
import {supabase,signIn,signOut,signUp} from './supabase';
import './styles.css';

type Service={name:string;price:number;description:string};
const services:Service[]=[{name:'Standard Clean',price:119,description:'Kitchen, bathrooms, bedrooms, floors and surfaces.'},{name:'Deep Clean',price:189,description:'A detailed top-to-bottom reset for your home.'},{name:'Move In / Out',price:249,description:'A thorough clean for moving day and empty spaces.'}];
type View='home'|'book'|'auth';

function App(){
 const[selected,setSelected]=useState(services[0]);const[view,setView]=useState<View>('home');const[user,setUser]=useState<User|null>(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 return <main><header><button className="brand brandBtn" onClick={()=>setView('home')}>Pure<span>Home</span></button><nav><a href="#services" onClick={()=>setView('home')}>Services</a><a href="#how" onClick={()=>setView('home')}>How it works</a>{user?<button className="ghost" onClick={()=>signOut()}>Sign out</button>:<button className="ghost" onClick={()=>setView('auth')}>Sign in</button>}</nav></header>
 {view==='auth'?<Auth done={()=>setView('home')}/>:view==='book'?<Booking service={selected} user={user} back={()=>setView('home')} account={()=>setView('auth')}/>:<Home choose={(s)=>{setSelected(s);setView('book')}}/>}
 <footer><b>PureHome</b><span>{user?`Signed in as ${user.email}`:'Clean home. Clear mind.'}</span></footer></main>
}
function Home({choose}:{choose:(s:Service)=>void}){return <><section className="hero"><div><p className="eyebrow">A cleaner home, without the hassle.</p><h1>Come home to <em>clean.</em></h1><p className="lede">Book trusted home cleaning in minutes. Simple pricing, dependable cleaners, and a home that feels fresh again.</p><div className="actions"><button className="primary" onClick={()=>choose(services[0])}>Book a cleaning</button><a href="#services">See services →</a></div><div className="trust"><b>✓ Secure booking</b><b>✓ Trusted cleaners</b><b>✓ Easy scheduling</b></div></div><div className="heroCard"><div className="sparkle">✦</div><h3>Your home deserves the reset.</h3><p>Flexible cleaning appointments built around your schedule.</p><div className="mini"><span>Next availability</span><strong>Choose your date</strong></div></div></section><section id="services" className="section"><p className="eyebrow">Cleaning made simple</p><h2>Choose your clean</h2><div className="cards">{services.map(s=><article key={s.name}><div className="icon">✦</div><h3>{s.name}</h3><p>{s.description}</p><div className="price">From <strong>${s.price}</strong></div><button onClick={()=>choose(s)}>Choose service</button></article>)}</div></section><section id="how" className="how"><p className="eyebrow">How PureHome works</p><h2>Clean home. Three easy steps.</h2><div className="steps"><div><b>01</b><h3>Choose your clean</h3><p>Select the service that fits your home.</p></div><div><b>02</b><h3>Pick your time</h3><p>Choose a date and time that works for you.</p></div><div><b>03</b><h3>Relax</h3><p>Your cleaner handles the rest.</p></div></div></section></>}
function Auth({done}:{done:()=>void}){const[mode,setMode]=useState<'in'|'up'>('in');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');const r=mode==='up'?await signUp(email,password,name):await signIn(email,password);setBusy(false);if(r.error)setMsg(r.error.message);else if(mode==='up'&&!r.data.session)setMsg('Check your email to confirm your PureHome account.');else done()}return <section className="auth"><div className="authCard"><p className="eyebrow">Welcome to PureHome</p><h1>{mode==='in'?'Sign in':'Create account'}</h1><p>{mode==='in'?'Access your bookings and account.':'Create your account to start booking cleanings.'}</p><form onSubmit={submit}>{mode==='up'&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{msg&&<p className="formMsg">{msg}</p>}<button className="primary full" disabled={busy}>{busy?'Please wait…':mode==='in'?'Sign in':'Create account'}</button></form><button className="switch" onClick={()=>{setMode(mode==='in'?'up':'in');setMsg('')}}>{mode==='in'?"New to PureHome? Create an account":"Already have an account? Sign in"}</button></div></section>}
function Booking({service,user,back,account}:{service:Service;user:User|null;back:()=>void;account:()=>void}){const[date,setDate]=useState('');const[address,setAddress]=useState('');return <section className="booking"><button className="back" onClick={back}>← Back</button><div className="bookingGrid"><div><p className="eyebrow">Book your clean</p><h1>{service.name}</h1><p>{service.description}</p><label>Service address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="123 Main Street"/></label><label>Preferred date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Notes<textarea placeholder="Anything your cleaner should know?"/></label></div><aside><h3>Booking summary</h3><div className="summary"><span>{service.name}</span><strong>${service.price}</strong></div><div className="summary"><span>Estimated total</span><strong>${service.price}</strong></div>{user?<button className="primary full" disabled={!date||!address}>Continue booking</button>:<button className="primary full" onClick={account}>Create account / Sign in</button>}<small>{user?'Booking API connection is the next step.':'Sign in before submitting a booking. No payment will be charged.'}</small></aside></div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
