import { createClient } from '@supabase/supabase-js';

export const supabase = createClient('https://iphxpqycoaqwjhecfajp.supabase.co','sb_publishable_RQun43vpCq23lsYKU2YB6g_5k1xQ4EI');
export async function signUp(email:string,password:string,fullName:string){return supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}});}
export async function signIn(email:string,password:string){return supabase.auth.signInWithPassword({email,password});}
export async function signOut(){return supabase.auth.signOut();}
export async function getMyRoles(){return supabase.from('user_roles').select('role');}
export async function getMyProfile(){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};return supabase.from('profiles').select('id,first_name,last_name,email,phone').eq('id',user.id).single();}
export async function updateMyProfile(input:{first_name:string;last_name:string;phone?:string}){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};const first_name=input.first_name.trim(),last_name=input.last_name.trim(),phone=input.phone?.trim()||'';if(!first_name||first_name.length>80)return{data:null,error:new Error('First name must be 1–80 characters')};if(!last_name||last_name.length>80)return{data:null,error:new Error('Last name must be 1–80 characters')};if(phone&&(phone.length<7||phone.length>30))return{data:null,error:new Error('Enter a valid phone number')};return supabase.from('profiles').update({first_name,last_name,phone:phone||null}).eq('id',user.id).select('id,first_name,last_name,email,phone').single();}
export async function getServices(){return supabase.from('services').select('id,name,description,base_price,estimated_minutes').eq('is_active',true).order('base_price');}
export async function getAddresses(){return supabase.from('customer_addresses').select('*').order('is_default',{ascending:false}).order('created_at');}
export async function deleteAddress(id:string){return supabase.from('customer_addresses').delete().eq('id',id);}
export async function setDefaultAddress(id:string){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};return supabase.schema('private').rpc('set_default_address',{p_address_id:id,p_customer_id:user.id});}
export async function addAddress(input:{address_line_1:string;address_line_2?:string;city:string;state:string;postal_code:string}){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};const address_line_1=input.address_line_1.trim(),address_line_2=input.address_line_2?.trim()||undefined,city=input.city.trim(),state=input.state.trim().toUpperCase(),postal_code=input.postal_code.trim();if(!address_line_1||address_line_1.length>150)return{data:null,error:new Error('Enter a valid street address')};if(address_line_2&&address_line_2.length>150)return{data:null,error:new Error('Address line 2 is too long')};if(!city||city.length>100)return{data:null,error:new Error('Enter a valid city')};if(!/^[A-Z]{2}$/.test(state))return{data:null,error:new Error('Enter a 2-letter state code')};if(!/^\d{5}$/.test(postal_code))return{data:null,error:new Error('Enter a 5-digit ZIP code')};return supabase.from('customer_addresses').insert({address_line_1,address_line_2,city,state,postal_code,customer_id:user.id,label:'Home',country:'US'}).select().single();}
export async function getMyBookings(){return supabase.from('bookings').select('id,booking_number,status,scheduled_start,scheduled_end,total,currency,created_at').order('scheduled_start',{ascending:false});}
export async function getBooking(booking_id:string){return supabase.from('bookings').select('id,booking_number,status,scheduled_start,scheduled_end,total,currency,created_at').eq('id',booking_id).single();}
export async function getAssignedCustomerContact(booking_id:string){return supabase.functions.invoke('get-customer-contact',{body:{booking_id}});}
export async function getCleanerAssignments(){return supabase.from('cleaner_assignments').select('id,booking_id,status,assigned_at,accepted_at,started_at,completed_at,cleaner_notes,bookings(id,booking_number,status,scheduled_start,scheduled_end,customer_notes,total,currency,customer_addresses(address_line_1,address_line_2,city,state,postal_code))').order('assigned_at',{ascending:false});}
export async function getAdminBookings(){return supabase.from('bookings').select('id,booking_number,customer_id,status,scheduled_start,scheduled_end,total,currency,customer_notes,created_at').order('scheduled_start',{ascending:false}).limit(100);}
export async function getAvailableCleaners(){return supabase.from('cleaner_profiles').select('user_id,rating,review_count,is_available,background_check_verified,hourly_rate').eq('is_available',true).order('rating',{ascending:false});}
export async function getProfiles(ids:string[]){if(!ids.length)return{data:[],error:null};return supabase.from('profiles').select('id,first_name,last_name,email,phone').in('id',ids);}
export async function assignCleaner(booking_id:string,cleaner_id:string){return supabase.functions.invoke('assign-cleaner',{body:{booking_id,cleaner_id}});}
export async function acceptAssignment(assignment_id:string){return supabase.functions.invoke('accept-assignment',{body:{assignment_id}});}
export async function completeJob(assignment_id:string,cleaner_notes?:string){return supabase.functions.invoke('complete-job',{body:{assignment_id,cleaner_notes}});}
export async function createBooking(input:{address_id:string;scheduled_start:string;scheduled_end:string;items:{service_id:string;quantity:number}[];customer_notes?:string}){return supabase.functions.invoke('create-booking',{body:input});}
export async function cancelBooking(booking_id:string,reason='Cancelled by customer'){return supabase.functions.invoke('cancel-booking',{body:{booking_id,reason}});}
export async function createPayment(booking_id:string){return supabase.functions.invoke('create-payment',{body:{booking_id}});}
export async function retryPayment(booking_id:string){return createPayment(booking_id);}

export async function markEnRoute(assignment_id:string){return supabase.functions.invoke('update-assignment-status',{body:{assignment_id,status:'en_route'}});}
export async function markArrived(assignment_id:string){return supabase.functions.invoke('update-assignment-status',{body:{assignment_id,status:'arrived'}});}
export async function startJob(assignment_id:string){return supabase.functions.invoke('update-assignment-status',{body:{assignment_id,status:'in_progress'}});}

export async function getNotifications(){return supabase.from('notifications').select('id,type,title,body,read_at,created_at,booking_id').order('created_at',{ascending:false}).limit(50);}
export async function markNotificationRead(id:string){return supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);}
export async function markAllNotificationsRead(){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};return supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null).select('id');}

export async function getCleanerProfile(){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};return supabase.from('cleaner_profiles').select('user_id,rating,review_count,hourly_rate,background_check_verified,is_available,service_radius_miles').eq('user_id',user.id).single();}
export async function setCleanerAvailability(is_available:boolean){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};return supabase.from('cleaner_profiles').update({is_available}).eq('user_id',user.id).select().single();}

export async function getReviewForBooking(booking_id:string){return supabase.from('reviews').select('id,rating,comment,created_at').eq('booking_id',booking_id).maybeSingle();}
export async function createReview(booking_id:string,rating:number,comment:string){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};const assignment=await supabase.from('cleaner_assignments').select('cleaner_id').eq('booking_id',booking_id).eq('status','completed').maybeSingle();if(assignment.error||!assignment.data?.cleaner_id)return{data:null,error:assignment.error??new Error('Completed cleaner assignment not found')};return supabase.from('reviews').insert({booking_id,customer_id:user.id,cleaner_id:assignment.data.cleaner_id,rating,comment:comment.trim()||null}).select().single();}

export async function getCleanerEarnings(){const{data:{user}}=await supabase.auth.getUser();if(!user)return{data:null,error:new Error('Please sign in first')};return supabase.from('cleaner_assignments').select('id,completed_at,bookings!inner(id,booking_number,total,currency,scheduled_start)').eq('cleaner_id',user.id).eq('status','completed').order('completed_at',{ascending:false});}

export async function getAdminServices(){return supabase.from('services').select('id,name,description,base_price,estimated_minutes,is_active').order('name');}
export async function updateService(id:string,changes:{base_price?:number;estimated_minutes?:number;is_active?:boolean}){return supabase.from('services').update(changes).eq('id',id).select().single();}

export async function getServiceAreas(){return supabase.from('service_areas').select('id,postal_code,city,state,is_active').order('postal_code');}
export async function addServiceArea(postal_code:string,city?:string,state?:string){return supabase.from('service_areas').insert({postal_code,city:city||null,state:state||null}).select().single();}
export async function updateServiceArea(id:string,is_active:boolean){return supabase.from('service_areas').update({is_active,updated_at:new Date().toISOString()}).eq('id',id).select().single();}

export async function checkServiceZip(postal_code:string){const exact=await supabase.from('service_areas').select('postal_code,radius_miles').eq('postal_code',postal_code).eq('is_active',true).maybeSingle();if(exact.data)return{data:{available:true},error:null};const zip=await supabase.from('service_zip_codes').select('latitude,longitude').eq('postal_code',postal_code).maybeSingle();if(zip.error)return{data:null,error:zip.error};if(!zip.data)return{data:{available:false},error:null};const areas=await supabase.from('service_areas').select('latitude,longitude,radius_miles').eq('is_active',true).not('radius_miles','is',null);if(areas.error)return{data:null,error:areas.error};const rad=(x:number)=>x*Math.PI/180;const available=(areas.data??[]).some((a:any)=>{if(a.latitude==null||a.longitude==null)return false;const dlat=rad(Number(zip.data!.latitude)-Number(a.latitude)),dlon=rad(Number(zip.data!.longitude)-Number(a.longitude));const h=Math.sin(dlat/2)**2+Math.cos(rad(Number(a.latitude)))*Math.cos(rad(Number(zip.data!.latitude)))*Math.sin(dlon/2)**2;return 3958.7613*2*Math.asin(Math.sqrt(h))<=Number(a.radius_miles)});return{data:{available},error:null};}
